// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.3
// source: v1/rule.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SaveRulesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rules []*SaveRulesRequest_Rule `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
}

func (x *SaveRulesRequest) Reset() {
	*x = SaveRulesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_rule_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveRulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveRulesRequest) ProtoMessage() {}

func (x *SaveRulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_rule_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveRulesRequest.ProtoReflect.Descriptor instead.
func (*SaveRulesRequest) Descriptor() ([]byte, []int) {
	return file_v1_rule_proto_rawDescGZIP(), []int{0}
}

func (x *SaveRulesRequest) GetRules() []*SaveRulesRequest_Rule {
	if x != nil {
		return x.Rules
	}
	return nil
}

type DeleteRulesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RuleIds []string `protobuf:"bytes,1,rep,name=rule_ids,json=ruleIds,proto3" json:"rule_ids,omitempty"`
}

func (x *DeleteRulesRequest) Reset() {
	*x = DeleteRulesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_rule_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteRulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRulesRequest) ProtoMessage() {}

func (x *DeleteRulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_rule_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRulesRequest.ProtoReflect.Descriptor instead.
func (*DeleteRulesRequest) Descriptor() ([]byte, []int) {
	return file_v1_rule_proto_rawDescGZIP(), []int{1}
}

func (x *DeleteRulesRequest) GetRuleIds() []string {
	if x != nil {
		return x.RuleIds
	}
	return nil
}

type RulesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rules []*RulesResponse_Rule `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
}

func (x *RulesResponse) Reset() {
	*x = RulesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_rule_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RulesResponse) ProtoMessage() {}

func (x *RulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_rule_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RulesResponse.ProtoReflect.Descriptor instead.
func (*RulesResponse) Descriptor() ([]byte, []int) {
	return file_v1_rule_proto_rawDescGZIP(), []int{2}
}

func (x *RulesResponse) GetRules() []*RulesResponse_Rule {
	if x != nil {
		return x.Rules
	}
	return nil
}

type SaveRulesRequest_Rule struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RuleId string `protobuf:"bytes,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	Type   string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	V0     string `protobuf:"bytes,3,opt,name=v0,proto3" json:"v0,omitempty"`
	V1     string `protobuf:"bytes,4,opt,name=v1,proto3" json:"v1,omitempty"`
	V2     string `protobuf:"bytes,5,opt,name=v2,proto3" json:"v2,omitempty"`
	V3     string `protobuf:"bytes,6,opt,name=v3,proto3" json:"v3,omitempty"`
	V4     string `protobuf:"bytes,7,opt,name=v4,proto3" json:"v4,omitempty"`
	V5     string `protobuf:"bytes,8,opt,name=v5,proto3" json:"v5,omitempty"`
}

func (x *SaveRulesRequest_Rule) Reset() {
	*x = SaveRulesRequest_Rule{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_rule_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveRulesRequest_Rule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveRulesRequest_Rule) ProtoMessage() {}

func (x *SaveRulesRequest_Rule) ProtoReflect() protoreflect.Message {
	mi := &file_v1_rule_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveRulesRequest_Rule.ProtoReflect.Descriptor instead.
func (*SaveRulesRequest_Rule) Descriptor() ([]byte, []int) {
	return file_v1_rule_proto_rawDescGZIP(), []int{0, 0}
}

func (x *SaveRulesRequest_Rule) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *SaveRulesRequest_Rule) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SaveRulesRequest_Rule) GetV0() string {
	if x != nil {
		return x.V0
	}
	return ""
}

func (x *SaveRulesRequest_Rule) GetV1() string {
	if x != nil {
		return x.V1
	}
	return ""
}

func (x *SaveRulesRequest_Rule) GetV2() string {
	if x != nil {
		return x.V2
	}
	return ""
}

func (x *SaveRulesRequest_Rule) GetV3() string {
	if x != nil {
		return x.V3
	}
	return ""
}

func (x *SaveRulesRequest_Rule) GetV4() string {
	if x != nil {
		return x.V4
	}
	return ""
}

func (x *SaveRulesRequest_Rule) GetV5() string {
	if x != nil {
		return x.V5
	}
	return ""
}

type RulesResponse_Rule struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RuleId string `protobuf:"bytes,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	Type   string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	V0     string `protobuf:"bytes,3,opt,name=v0,proto3" json:"v0,omitempty"`
	V1     string `protobuf:"bytes,4,opt,name=v1,proto3" json:"v1,omitempty"`
	V2     string `protobuf:"bytes,5,opt,name=v2,proto3" json:"v2,omitempty"`
	V3     string `protobuf:"bytes,6,opt,name=v3,proto3" json:"v3,omitempty"`
	V4     string `protobuf:"bytes,7,opt,name=v4,proto3" json:"v4,omitempty"`
	V5     string `protobuf:"bytes,8,opt,name=v5,proto3" json:"v5,omitempty"`
}

func (x *RulesResponse_Rule) Reset() {
	*x = RulesResponse_Rule{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_rule_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RulesResponse_Rule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RulesResponse_Rule) ProtoMessage() {}

func (x *RulesResponse_Rule) ProtoReflect() protoreflect.Message {
	mi := &file_v1_rule_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RulesResponse_Rule.ProtoReflect.Descriptor instead.
func (*RulesResponse_Rule) Descriptor() ([]byte, []int) {
	return file_v1_rule_proto_rawDescGZIP(), []int{2, 0}
}

func (x *RulesResponse_Rule) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *RulesResponse_Rule) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RulesResponse_Rule) GetV0() string {
	if x != nil {
		return x.V0
	}
	return ""
}

func (x *RulesResponse_Rule) GetV1() string {
	if x != nil {
		return x.V1
	}
	return ""
}

func (x *RulesResponse_Rule) GetV2() string {
	if x != nil {
		return x.V2
	}
	return ""
}

func (x *RulesResponse_Rule) GetV3() string {
	if x != nil {
		return x.V3
	}
	return ""
}

func (x *RulesResponse_Rule) GetV4() string {
	if x != nil {
		return x.V4
	}
	return ""
}

func (x *RulesResponse_Rule) GetV5() string {
	if x != nil {
		return x.V5
	}
	return ""
}

var File_v1_rule_proto protoreflect.FileDescriptor

var file_v1_rule_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x76, 0x31, 0x2f, 0x72, 0x75, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xdf, 0x01, 0x0a, 0x10, 0x53, 0x61, 0x76, 0x65, 0x52,
	0x75, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x35, 0x0a, 0x05, 0x72,
	0x75, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x05, 0x72, 0x75, 0x6c,
	0x65, 0x73, 0x1a, 0x93, 0x01, 0x0a, 0x04, 0x52, 0x75, 0x6c, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x72,
	0x75, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x75,
	0x6c, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x76, 0x30, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x76, 0x30, 0x12, 0x0e, 0x0a, 0x02, 0x76, 0x31, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x76, 0x31, 0x12, 0x0e, 0x0a, 0x02, 0x76, 0x32, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x76, 0x32, 0x12, 0x0e, 0x0a, 0x02, 0x76, 0x33, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x76, 0x33, 0x12, 0x0e, 0x0a, 0x02, 0x76, 0x34, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x76, 0x34, 0x12, 0x0e, 0x0a, 0x02, 0x76, 0x35, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x76, 0x35, 0x22, 0x2f, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19,
	0x0a, 0x08, 0x72, 0x75, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x07, 0x72, 0x75, 0x6c, 0x65, 0x49, 0x64, 0x73, 0x22, 0xd9, 0x01, 0x0a, 0x0d, 0x52, 0x75,
	0x6c, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x05, 0x72,
	0x75, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x2e, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x05, 0x72, 0x75, 0x6c, 0x65, 0x73, 0x1a,
	0x93, 0x01, 0x0a, 0x04, 0x52, 0x75, 0x6c, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x75, 0x6c, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x75, 0x6c, 0x65, 0x49,
	0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x76, 0x30, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x76, 0x30, 0x12, 0x0e, 0x0a, 0x02, 0x76, 0x31, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x76, 0x31, 0x12, 0x0e, 0x0a, 0x02, 0x76, 0x32, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x76, 0x32, 0x12, 0x0e, 0x0a, 0x02, 0x76, 0x33, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x76, 0x33, 0x12, 0x0e, 0x0a, 0x02, 0x76, 0x34, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x76, 0x34, 0x12, 0x0e, 0x0a, 0x02, 0x76, 0x35, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x76, 0x35, 0x32, 0xc9, 0x01, 0x0a, 0x04, 0x52, 0x75, 0x6c, 0x65, 0x12, 0x3f,
	0x0a, 0x09, 0x53, 0x61, 0x76, 0x65, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x12, 0x1a, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x52, 0x75, 0x6c, 0x65, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12,
	0x43, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x12, 0x1c,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x52, 0x75, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x12, 0x3b, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x52, 0x75, 0x6c, 0x65, 0x73,
	0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x76, 0x31, 0x2e, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x47, 0x0a, 0x1b, 0x6f, 0x72, 0x67, 0x2e, 0x66, 0x75, 0x6e, 0x63, 0x61, 0x72, 0x64,
	0x73, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x7a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x76, 0x31,
	0x42, 0x09, 0x52, 0x75, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x05, 0x2e,
	0x2f, 0x3b, 0x76, 0x31, 0xaa, 0x02, 0x13, 0x46, 0x75, 0x6e, 0x43, 0x61, 0x72, 0x64, 0x73, 0x4f,
	0x72, 0x67, 0x2e, 0x47, 0x72, 0x70, 0x63, 0x2e, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_v1_rule_proto_rawDescOnce sync.Once
	file_v1_rule_proto_rawDescData = file_v1_rule_proto_rawDesc
)

func file_v1_rule_proto_rawDescGZIP() []byte {
	file_v1_rule_proto_rawDescOnce.Do(func() {
		file_v1_rule_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_rule_proto_rawDescData)
	})
	return file_v1_rule_proto_rawDescData
}

var file_v1_rule_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_v1_rule_proto_goTypes = []interface{}{
	(*SaveRulesRequest)(nil),      // 0: proto.v1.SaveRulesRequest
	(*DeleteRulesRequest)(nil),    // 1: proto.v1.DeleteRulesRequest
	(*RulesResponse)(nil),         // 2: proto.v1.RulesResponse
	(*SaveRulesRequest_Rule)(nil), // 3: proto.v1.SaveRulesRequest.Rule
	(*RulesResponse_Rule)(nil),    // 4: proto.v1.RulesResponse.Rule
	(*emptypb.Empty)(nil),         // 5: google.protobuf.Empty
}
var file_v1_rule_proto_depIdxs = []int32{
	3, // 0: proto.v1.SaveRulesRequest.rules:type_name -> proto.v1.SaveRulesRequest.Rule
	4, // 1: proto.v1.RulesResponse.rules:type_name -> proto.v1.RulesResponse.Rule
	0, // 2: proto.v1.Rule.SaveRules:input_type -> proto.v1.SaveRulesRequest
	1, // 3: proto.v1.Rule.DeleteRules:input_type -> proto.v1.DeleteRulesRequest
	5, // 4: proto.v1.Rule.GetRules:input_type -> google.protobuf.Empty
	5, // 5: proto.v1.Rule.SaveRules:output_type -> google.protobuf.Empty
	5, // 6: proto.v1.Rule.DeleteRules:output_type -> google.protobuf.Empty
	2, // 7: proto.v1.Rule.GetRules:output_type -> proto.v1.RulesResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_v1_rule_proto_init() }
func file_v1_rule_proto_init() {
	if File_v1_rule_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_v1_rule_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveRulesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_rule_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteRulesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_rule_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RulesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_rule_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveRulesRequest_Rule); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_rule_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RulesResponse_Rule); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_rule_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_rule_proto_goTypes,
		DependencyIndexes: file_v1_rule_proto_depIdxs,
		MessageInfos:      file_v1_rule_proto_msgTypes,
	}.Build()
	File_v1_rule_proto = out.File
	file_v1_rule_proto_rawDesc = nil
	file_v1_rule_proto_goTypes = nil
	file_v1_rule_proto_depIdxs = nil
}
